services:
  bfpt:
    image: denoland/deno
    container_name: bfpt
    restart: always
    volumes:
      - .:/app
      - deno-cache:/deno-dir
    working_dir: /app
    environment:
      - DB_HOST=bfpt-db
      - DB_PASSWORD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    #depends_on:
    #  - bfpt-db
    command: deno task start
    ports:
      - "8000:8000"

  bfpt-db:
    image: mariadb
    container_name: bfpt-db
    environment:
      MYSQL_ROOT_PASSWORD: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      MYSQL_DATABASE: bfpt
      MYSQL_USER: bfpt
      MYSQL_PASSWORD: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  bfpt-adminer:
    image: adminer
    container_name: bfpt-adminer
    restart: always
    ports:
      - "8080:8080"
    profiles:
      - adminer

volumes:
  deno-cache:
  db-data:
