services:
  bfpt:
    image: denoland/deno
    container_name: bfpt
    restart: always
    volumes:
      - .:/app
      - deno-cache:/deno-dir
    working_dir: /app
    environment:
      - DB_HOST=bfpt-db
      - DB_PASSWORD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
    command: deno task start
    ports:
      - '8000:8000'

  bfpt-db:
    image: postgres
    restart: always
    container_name: bfpt-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      - POSTGRES_DB=bfpt
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql 

  bfpt-pgadmin:
    container_name: bfpt-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    profiles:
      - pgadmin

volumes:
  deno-cache:
  db-data: